### PR TITLE
exits handler on producer connection going away

### PR DESCRIPTION
**Pull request by thinktainer**

### CODE REVIEW

**Comment by mjgarton** [comment]
This seems to change multiple things. Is that intentional?

**Comment by SpeedyCoder** [comment]
I think I would rather get this merged https://github.com/uw-labs/proximo/pull/73 and then make these changes in substrate

**Comment by thinktainer** [comment]
> This seems to change multiple things. Is that intentional?

I can take back the change to golang version, if we think this is controversial?

**Comment by SpeedyCoder** [comment]
added to substrate already

**Pull request closed without merging**
