### PR TITLE
Move proto files to separate package.

### PR DESCRIPTION
**Pull request by SpeedyCoder**

### CODE REVIEW

**Comment by SpeedyCoder** [comment]
My thinking was to switch substrate to use those and then remove `proximoc-go` altogether after adding the old client to `go-pubsub`. We could hide them, but we would then have to generate them in substrate if we want to remove the old client...

**Comment by mjgarton** [comment]
I'd prefer not to share generated code between proximo and substrate.  Generating is such a trivial thing (2 lines of Makefile or .sh file) , I don't think it's worth the added cross-project dependency.

**Comment by SpeedyCoder** [comment]
Fair enough, though the substrate proximo backend is always going to depend on the proto definitions in proximo 😄

**Comment by SpeedyCoder** [comment]
Also, it would make it a bit more work to turn the server into a library as we would have to expose functions for registering the servers and introduce new type for offset when we implement it...
Though, it would make the interface of the package smaller what is a quite nice benefit.

**Pull request merged**
